// src/generators/shared/git.ts

import { run, runSafe } from '../../utils/exec.js';

export async function initGit(targetDir: string, projectName: string): Promise<void> {
  // Check if git is available
  const gitCheck = await runSafe('git --version');
  if (!gitCheck.ok) {
    throw new Error('Git is not installed or not in PATH');
  }

  // Check if already a git repo
  const isRepo = await runSafe('git rev-parse --is-inside-work-tree', { cwd: targetDir });
  if (isRepo.ok) return; // Already initialized (some frameworks do this)

  await run('git init', { cwd: targetDir });
  await run('git add -A', { cwd: targetDir });

  const commitMessage = `feat: initial project scaffold

Generated by KeroDev CLI
Project: ${projectName}
Timestamp: ${new Date().toISOString()}`;

  await run(`git commit -m "${commitMessage}"`, { cwd: targetDir });
}

export async function setRemote(targetDir: string, remoteUrl: string): Promise<void> {
  await run(`git remote add origin ${remoteUrl}`, { cwd: targetDir });
}
