// src/generators/flutter/configs/pubspec.ts

import type { FlutterProjectConfig } from '../../../types/index.js';

export function generatePubspec(config: FlutterProjectConfig): string {
  const safeName = config.name.replace(/-/g, '_');
  const deps = buildDependencies(config);
  const devDeps = buildDevDependencies(config);

  return `name: ${safeName}
description: ${config.name} — Generated by KeroDev CLI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
${deps.map(d => `  ${d}`).join('\n')}

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
${devDeps.map(d => `  ${d}`).join('\n')}

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: AppFont
      fonts:
        - asset: assets/fonts/AppFont-Regular.ttf
        - asset: assets/fonts/AppFont-Bold.ttf
          weight: 700
`;
}

function buildDependencies(config: FlutterProjectConfig): string[] {
  const deps: string[] = [
    '# ─── State Management ────────────────────────────────────────',
    ...stateManagerDeps(config.stateManager),
    '',
    '# ─── Navigation ─────────────────────────────────────────────',
  ];

  if (config.features.goRouter) {
    deps.push('go_router: ^14.0.0');
  }

  deps.push('', '# ─── Network ─────────────────────────────────────────────');

  if (config.features.dio) {
    deps.push('dio: ^5.4.0', 'pretty_dio_logger: ^1.3.0');
  }

  if (config.features.retrofit) {
    deps.push('retrofit: ^4.1.0', 'json_annotation: ^4.8.0');
  }

  deps.push('', '# ─── Storage ─────────────────────────────────────────────');

  if (config.features.hive) {
    deps.push('hive: ^2.2.3', 'hive_flutter: ^1.1.0');
  }
  if (config.features.isar) {
    deps.push('isar: ^3.1.0', 'isar_flutter_libs: ^3.1.0', 'path_provider: ^2.1.0');
  }
  if (!config.features.hive && !config.features.isar) {
    deps.push('shared_preferences: ^2.2.0');
  }

  deps.push('', '# ─── Firebase ────────────────────────────────────────────');
  if (config.features.firebase) {
    deps.push(
      'firebase_core: ^3.0.0',
      'firebase_auth: ^5.0.0',
      'cloud_firestore: ^5.0.0',
      'firebase_storage: ^12.0.0',
    );
  }

  if (config.features.supabase) {
    deps.push('', '# ─── Supabase ────────────────────────────────────────────');
    deps.push('supabase_flutter: ^2.3.0');
  }

  deps.push(
    '',
    '# ─── UI & Utils ──────────────────────────────────────────────',
    'flutter_screenutil: ^5.9.0',
    'cached_network_image: ^3.3.0',
    'shimmer: ^3.0.0',
    'fluttertoast: ^8.2.4',
    'flutter_svg: ^2.0.10',
    'intl: ^0.19.0',
    'equatable: ^2.0.5',
    'dartz: ^0.10.1',
    'freezed_annotation: ^2.4.1',
  );

  if (config.features.localization) {
    deps.push('flutter_localizations:\n    sdk: flutter', 'intl: ^0.19.0');
  }

  return deps;
}

function stateManagerDeps(sm: FlutterProjectConfig['stateManager']): string[] {
  switch (sm) {
    case 'riverpod':
      return [
        'flutter_riverpod: ^2.5.0',
        'riverpod_annotation: ^2.3.0',
        'hooks_riverpod: ^2.5.0',
        'flutter_hooks: ^0.20.5',
      ];
    case 'bloc':
      return ['flutter_bloc: ^8.1.4', 'bloc: ^8.1.3', 'hydrated_bloc: ^9.1.4'];
    case 'cubit':
      return ['flutter_bloc: ^8.1.4', 'bloc: ^8.1.3'];
    case 'getx':
      return ['get: ^4.6.6'];
    case 'provider':
      return ['provider: ^6.1.2'];
  }
}

function buildDevDependencies(config: FlutterProjectConfig): string[] {
  const devDeps: string[] = ['build_runner: ^2.4.8', 'freezed: ^2.4.6'];

  if (config.features.retrofit) {
    devDeps.push('retrofit_generator: ^8.0.0', 'json_serializable: ^6.7.1');
  }
  if (config.stateManager === 'riverpod') {
    devDeps.push('riverpod_generator: ^2.3.0', 'custom_lint: ^0.6.2', 'riverpod_lint: ^2.3.0');
  }
  if (config.features.hive) {
    devDeps.push('hive_generator: ^2.0.1');
  }
  if (config.features.isar) {
    devDeps.push('isar_generator: ^3.1.0');
  }

  devDeps.push('mockito: ^5.4.4', 'bloc_test: ^9.1.6');

  return devDeps;
}
